# Generated by ChatGPT on 2026-01-14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='carga_horaria',
        ),
        migrations.CreateModel(
            name='CursoAgendamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data do curso')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='certificados.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Agendamento de curso',
                'verbose_name_plural': 'Agendamentos de cursos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='certificados.cursoagendamento', verbose_name='Agendamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='certificados.cliente', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.UniqueConstraint(fields=('agendamento', 'cliente'), name='uniq_inscricao_agendamento_cliente'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='certificados.cursoagendamento', verbose_name='Agendamento'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(fields=('cliente', 'curso', 'agendamento'), name='uniq_cert_cliente_curso_agendamento'),
        ),
    ]
