# Generated by Django 4.2.15 on 2026-01-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_agendamento_e_email_e_remover_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria_padrao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga horária (horas)'),
        ),
    ]
