# Generated by Django 4.2.15 on 2026-02-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(default='Não Informado', max_length=200, verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
