# Generated by Django 4.2.15 on 2026-04-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0006_questionario_pergunta_respostausuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cargo', models.CharField(blank=True, max_length=200, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='itemrespostausuario',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.pergunta', verbose_name='Pergunta'),
        ),
        migrations.AddField(
            model_name='cursoagendamento',
            name='instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='certificados.instrutor', verbose_name='Instrutor'),
        ),
    ]
